global using Client.Library.Endpoints.Interfaces;
global using Client.Library.LocalStorage.Interfaces;
global using Client.Library.Models;
global using Microsoft.AspNetCore.Components.WebAssembly.Authentication;
global using System.Net.Http.Json;
global using Client.Library.Models.Cache;
global using Microsoft.AspNetCore.Components.Forms;
global using Blazored.LocalStorage;
global using Client.Library.Models.Display;